# Site settings
title: NewCareerJourney
header-img: img/home-bg.png
email: ctlee9096@gmail.com
copyright_name: ICanDoAllThingThroughChrist
description: > # this means to ignore newlines until "baseurl:"
  an midlife immigrants journey toward a new career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ICanDoAllThingThroughChrist
learn_profile: ICanDoAllThingThroughChrist
email_username: ctlee9096@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
